### ISSUE TITLE
Be able to switch between 128-bit and 256-bit

### ISSUE THREAD

**Issue by ghost** [noprotocol/php-mysql-aes-crypt#8]
Hi!

As it is right now, the class will only encrypt in 128-bit AES. In order to change it to 256-bit, you must change `AES-128-ECB` on the rows 39, 45, and 65 to `AES-256-ECB`. When the class is being updated, you must change it manually once more.

To prevent this, add a extra variable to the class, like this:

```PHP
    public function encrypt($data, $bit)
    {
        $chiperIvLength = openssl_cipher_iv_length('AES-'.$bit.'-ECB');
        $iv = openssl_random_pseudo_bytes($chiperIvLength);
        $padValue = 16 - (strlen($data) % 16);
        return openssl_encrypt(
            str_pad($data, (16 * (floor(strlen($data) / 16) + 1)), chr($padValue)),
            'AES-'.$bit.'-ECB',
            $this->key,
            OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING,
            $iv
        );
    }
```

```PHP
    public function decrypt($data, $bit)
    {
        $data = openssl_decrypt(
            $data,
            'AES-'.$bit.'-ECB',
            $this->key,
            OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING
        );
```

Then use `$crypter->decrypt($string, '256');` to encrypt the string with 256-bit AES.

I have no idea if this will work, but you get the idea. So, please add this!

**Comment by annejan** [comment]
I have a different (nicer) idea to solve this, will get back on this tomorrow :-)

**Comment by ghost** [comment]
Sweet! How's it going with the idea? :)

**Comment by verschuur** [comment]
Nice one AJ 👌🏼

**Comment by annejan** [comment]
You can now optionally choose a cypher in the constructor, eg:
```php
<?php
$crypter = new Crypter('mykeystring', 'AES-256-ECB');
```

**Comment by ghost** [comment]
Really nice!
